// <auto-generated />
using System;
using Mac.MAUI.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mac.MAUI.Data.Migrations
{
    [DbContext(typeof(MacAppContext))]
    partial class MacAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mac.MAUI.Data.Models.Contrato", b =>
                {
                    b.Property<int>("Id_Contrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Contrato"));

                    b.Property<DateTime>("Dt_DataVenda")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Fl_Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nm_Bloco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nm_Contrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nm_Empreendimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nm_Unidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Contrato");

                    b.ToTable("Contrato");
                });
#pragma warning restore 612, 618
        }
    }
}
